### ISSUE TITLE
Setting up public repo

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#1]
**Setting up the public repo `socialincome-san/public` includes (non-exhaustive list):**  

- [x] GitHub actions for deployment
- [x] Settings for merging into the main branch through PRs (approval from one of the admins before they can be merged)
- [x] Only admins can deploy or add secrets
- [ ] Basic folder structure for code base (mobile, website, admin and shared files and typesafe collection definitions)

**Comment by andrashee** [comment]
I think the most crucial settings / deployments are done. I haven't tested it with a non admin user. @ssandino do you have one?
