### ISSUE TITLE
[UI] Proofread readme.md and contributing.md

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#108]
Proofreading following files:

- [UI Readme](https://github.com/socialincome-san/public/tree/main/ui)
- [Contribution.md](https://github.com/socialincome-san/public/blob/main/ui/CONTRIBUTION.md)

(same as you did for the main readme.md)

**Comment by jeslyw** [comment]
sure - please assign :)

**Comment by jeslyw** [comment]
[PR](https://github.com/socialincome-san/public/pull/116) done :)
