### ISSUE TITLE
Backup Strategy Plan

### ISSUE THREAD

**Issue by andrashee** [socialincome-san/public#113]
Test and document firestore database backup restore

**Comment by ssandino** [comment]
> A custom firebase functions schedules the export on an hourly basis. We currently have one deployed, but I can't find the source anywhere. I think Juan might have created it adhoc somewhere. Once the restructuring PR of @mkue is in the main branch, I will create a function similar to the one [here](https://firebase.google.com/docs/firestore/solutions/schedule-export).

I think it was done directly in the console (might be the [Cloud Schedular tool](https://console.cloud.google.com/cloudscheduler/)). That might be why there is not much trace of it in the code.

**Comment by ssandino** [comment]
@andrashee can we close this? With the hourly backups and the new log file, it seems fine for now.
