### ISSUE TITLE
[DevOps]: Add dependabot version update PRs

### ISSUE THREAD

**Issue by renestalder** [socialincome-san/public#136]
The repository is currently configured for checking for security update. We should also ensure regular automatic version updates to have better control about the dependencies not going stale.

Add dependabot version update PRs as soon as it properly supports npm workspaces.

* See for https://github.com/dependabot/dependabot-core/issues/4993 to get resolved
* Activate `Dependabot version updates` in "Security" settings of the project and customize the GitHub action proposed by that button.

_Issue stands as a reminder that I already tried that, but saw that there is a blocker of doing it right now_.

**Comment by ssandino** [comment]
@renestalder can we close this?

**Comment by ssandino** [comment]
Update: the issue [Dependabot doesn't work properly with monorepos](https://github.com/dependabot/dependabot-core/issues/4993) is resolved
