### ISSUE TITLE
[UI / Design Feature]: Add form field UI components

### ISSUE THREAD

**Issue by renestalder** [socialincome-san/public#138]
**What kind of UI element or design specification is missing from the
design system**.

Accessible form field components.

**What other solutions have you already considered to use**

None.

**Additional context** Add any other context or screenshots about the
feature request here.

- Must have built-in validation states (HTML5 client-side validations are not always accessible)
- Is part of #84 
- Possibly blocks work in the survey tool

**Comment by ssandino** [comment]
If possible, it would be nice to use the _floating outlined form fields_ (like [here](https://notiz.dev/blog/floating-form-field-with-tailwindcss#outline-form-field) except some additional rounded corners)
