### ISSUE TITLE
Admin tool doesn't save changes anymore due to a 

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#145]
**Describe the bug** A clear and concise description of what the bug is.
We can't save changes in the admin tool anymore (due to a problem in a date field)

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'recipients'
2. Change value in any 'test user'
3. See error

**Expected behavior** A clear and concise description of what you
expected to happen.

**Screenshots** If applicable, add screenshots to help explain your
problem.
<img width="1267" alt="Screenshot 2022-10-26 at 18 53 29" src="https://user-images.githubusercontent.com/6095849/198087894-578c9537-f502-42b4-81e5-544c5347fb50.png">

**Desktop (please complete the following information):**

- OS: 13.0 Ventura
- Safari 16.1

**Comment by ssandino** [comment]
@andrashee @mkue any clue?

**Comment by andrashee** [comment]
I can reproduce this locally as well. Seems like a firecms bug. Maybe [this change](https://github.com/Camberi/firecms/commit/bf5a3af9f018e2e490e0f422b3bfa47df498457e#diff-5af2da65dd3d662feb8f7cc2ade98a694423dad2afe946d5f58a7bf9c6d81ef3R514) caused it.
The newest version (41) also has the same issue, rolled it back to version which works with https://github.com/socialincome-san/public/pull/146

**Comment by fgatti675** [comment]
This should be fixed in the latest version :)
I take the chance to invite you to the official Discord channel of FireCMS: https://discord.gg/fxy7xsQm3m
Also, it would help us a lot to have a call with you to see how FireCMS is working out for you and if there is anything we can do to improve it. It would be great if you could reach me at francesco@camberi.com 🙌

**Comment by andrashee** [comment]
Thanks a lot @fgatti675 for your quick fix! Highly appreciated.
We would love to have a call with you. I think @ssandino will reach out to you :-)
