### ISSUE TITLE
[Website Feature]: Migrate Firebase Functions

### ISSUE THREAD

**Issue by andrashee** [socialincome-san/public#15]
In the website repository, we have a bunch of backend / etl functions. 
As a next step, I would like to 
- migrate them from vanilla javascript to typescript
- migrate them into this public repository

**Comment by ssandino** [comment]
@andrashee seems to be done, right?

**Comment by andrashee** [comment]
No, there are still quite some missing.

**Comment by ssandino** [comment]
@andrashee, I believe we can close this issue. It seems that some functions related to confirmation/payment emails weren't transferred to the new repo. We can address these with individual issues moving forward, instead of keeping this general one open.
