### ISSUE TITLE
Adding codemagic support for automatic build pipelines for android and iOS

### ISSUE THREAD

**Issue by novas1r1** [socialincome-san/public#186]
**Is your feature request related to a problem? Please describe.** 
Currently we have to manually push new releases to the stores. Especially for Apple that's no fun at all.

**Describe the solution/feature** 
Codemagic will provide an android and iOS build pipeline where new builds can be triggered (automatically or manually) and the this build will automatically be published to the stores.

**Describe alternatives you've considered**
Bitrise would have been an alternative, or fastlane, but we decided for Codemagic because of the experience.

**Additional context**

**Comment by ssandino** [comment]
Update @ all: we have now an unlimited version (software sponsorship) of [codemagic](https://codemagic.io/start/).

**Comment by novas1r1** [comment]
I'll sit down around Christmas to create running pipelines :)!

**Comment by ssandino** [comment]
@novas1r1 should we close this as it seems to be working fine

**Comment by novas1r1** [comment]
@ssandino yes :) closing it
