### ISSUE TITLE
Add Search Bar

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#20]
**Is your feature request related to a problem? Please describe.**
It's sometimes difficult to find a specific recipient or contributor in the list (as the sorting/filtering is not always working)

**Describe the solution you'd like**
Adding a search bar like in the [demo](https://demo.firecms.co/c/blog). See also [FireCMS Documentation](https://github.com/Camberi/firecms/tree/next)

Priorities:
- global admins can search all lists (except local ngo and adminstrators list are too small to be searchable)
- If NGO administrators can NOT search out of the box, then we would add this to the long list (as it's most likely lots of effort and the added value not huge)

**Additional context**
We do have an Algolia NGO-account. We may have to add the [Agolia Firebase Extension](https://firebase.google.com/products/extensions/algolia-firestore-algolia-search).

**Comment by andrashee** [comment]
Managed to setup a sync function using for the recipients using the extension. 
Manually import the existing ones.

Will now work on the code changes and document it.

**Comment by mkue** [comment]
It seems like you already implemented this @andrashee?

@ssandino, do you want to have the search bar for any other than the recipients collection?

**Comment by ssandino** [comment]
If possible yes! Not sure how it works within the pre-filtered NGO view. Possible?

**Comment by andrashee** [comment]
> It seems like you already implemented this @andrashee?
> 

Half done.

I used the firestore algolia extension to export the data to algolia. However, this seems to be limited to one collection afaik.

I think we should replace the extension with a firestore trigger function which we code by ourselves to not limit ourselves.

**Comment by andrashee** [comment]
The firecms example has also an implementation if the sync: https://github.com/Camberi/firecms/blob/master/example_backend/functions/src/algolia.ts

**Comment by mkue** [comment]
Cool! Lets' do that then?

**Comment by ssandino** [comment]
Possible to add it for the contributor `users` list too?
