### ISSUE TITLE
[DevOps Bug]: Fix `website:serve` script in package.json

### ISSUE THREAD

**Issue by mkue** [socialincome-san/public#229]
**Describe the bug** A clear and concise description of what the bug is.

`website:serve` should work with local firebase emulator that have been started with `firebase:serve`.

**Additional context** Add any other context about the problem here.

Currently, the command crashes with `error - Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.` as soon as one tries to open the website locally.

**Comment by mkue** [comment]
Shouldn't all scripts behave the same way? I would've assumed that '*:serve' scripts connect to the local emulator that has been started with 'firbase:serve'. This makes sure that we can run multiple projects simultaneously, which isn't possible at the moment (you can't run the admin and the website and I think that should be possible).
In the end, this is just about setting some env variables the 'website/.env' file so that the 'initializeApp()' call does not crash, as far as I can tell.
I'll look into it👌🏼

**Comment by mkue** [comment]
I don't mind having a separate 'website:serve:emulator' call that can be used if you just work on the website project.

**Comment by andrashee** [comment]
> Shouldn't all scripts behave the same way? I would've assumed that '*:serve' scripts connect to the local emulator that has been started with 'firbase:serve'. This makes sure that we can run multiple projects simultaneously, which isn't possible at the moment (you can't run the admin and the website and I think that should be possible).
> In the end, this is just about setting some env variables the 'website/.env' file so that the 'initializeApp()' call does not crash, as far as I can tell.
> I'll look into it👌🏼

You're right, make sense 👍
Yes, I also think that we just need to set the env variables which are implicitly available when we start with the `firebase emulator exec`.
