### ISSUE TITLE
[Mobile App Feature]: Enable AppCheck to verify requests

### ISSUE THREAD

**Issue by novas1r1** [socialincome-san/public#234]
**Is your feature request related to a problem? Please describe.** 
AppCheck monitors from where the requests to Firebase are coming. Within the Firebase Console we can enable to enforce only verified requests from our app and admin tool. That would highly increase our security as well makes it possible to commit the GoogleService-Info.plist file to git.

**Describe the solution/feature** 
See above

**Describe alternatives you've considered** 
Leaving it like it is now is the alternative - wouldn't recommend since implementing AppCheck is easy.

**Additional context** 
We should enable AppCheck as soon as possible. As soon as all systems are using AppCheck and all apps have been updated to the current version we can enable enforcement for verified requests in the Firebase Console.
https://firebase.google.com/docs/app-check

**Comment by ssandino** [comment]
@mkue @andrashee what you think?

**Comment by mkue** [comment]
Yes, definitely! Sounds like a must-have. Thanks for bringing this up.

**Comment by ssandino** [comment]
to be discussed in relation to the web app (admin or website) (I'll bring it up later, but please go ahead with the app)
