### ISSUE TITLE
Total donation number on transparency page wrong

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#235]
**Describe the bug** 
The total donation amount seems to high. It was brought to the attention by user:
"Ihr führt auf noch auszubezahlen 158'528 CHF, aber unter Reserven führt ihr nur ein Guthaben auf dem Bankkonto von 68’037 CHF auf.  Wo sind die restlichen 90’491 CHF, welche ihr noch auszahlen wollt oder was verstehe ich falsch?"

**To Reproduce**
See: https://socialincome.org/finances

**Expected number**
Best guess: Balance on bank is counted as donation + 25k from DEZA counted

**Comment by andrashee** [comment]
Thanks for raising! I will have a look at it 👍
