### ISSUE TITLE
[Mobile App Feature]:  Create UI Components

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#264]
**Is your feature request related to a problem? Please describe.** 
Create the new components for the app. 

Optional: use the flutter storybook if it makes sense!

**Comment by novas1r1** [comment]
This is the design from raphael: https://xd.adobe.com/view/503d8f3f-704a-499c-b943-0868a4d8493d-056e/specs/

**Comment by ssandino** [comment]
@novas1r1 can we close this as the "standard library" of UI components have been implemented

**Comment by novas1r1** [comment]
This is done.
