### ISSUE TITLE
Optimize view for organisation admins

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#294]
**Is your feature request related to a problem? Please describe.**
NGO view (when you login as NGO partner) can be improved. This also helps for a better use and therefore better data quality. 

**Describe the solution/feature**
1. Hide `Partner Organisation` Tile
2. Make a new VERY simple input mask for new potential recipients with the fields `first name`, `last name`, `contact phone` (plus give it automatically "waiting list" + reference to org.)
3. Take away "add new recipients" button in the `recipients tile` (they will be able to add new recipients with the new input mask (Nr. 2 above)
![Image](https://user-images.githubusercontent.com/6095849/221996481-14e2dca5-05bd-44a9-b48a-96b373018068.png)
4. The field "OM UID" should be non-editable for org. admins

**Comment by ssandino** [comment]
Fix Tile Payment Confirmation

**Comment by Dariusz385** [comment]
> **Is your feature request related to a problem? Please describe.** NGO view (when you login as NGO partner) can be improved. This also helps for a better use and therefore better data quality.
> 
> **Describe the solution/feature**
> 
> 1. Hide `Partner Organisation` Tile
> 2. Make a new VERY simple input mask for new potential recipients with the fields `first name`, `last name`, `contact phone` (plus give it automatically "waiting list" + reference to org.)
> 3. Take away "add new recipients" button in the `recipients tile` (they will be able to add new recipients with the new input mask (Nr. 2 above)
>    ![Image](https://user-images.githubusercontent.com/6095849/221996481-14e2dca5-05bd-44a9-b48a-96b373018068.png)
> 4. The field "OM UID" should be non-editable for org. admins
