### ISSUE TITLE
Transparency stats: recurring revenue shows 0

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#296]
**Describe the bug**
Since the last update the recurring revenues shows 0

**To Reproduce** 
Visit transparency page
<img width="592" alt="Screenshot 2023-01-26 at 10 58 23" src="https://user-images.githubusercontent.com/6095849/214807963-84dcb2a8-21bc-4cb0-95f3-11047e24b41c.png">

**Comment by andrashee** [comment]
Removed it. Would like to redo this page anyhow in the new page. https://github.com/socialincome-san/soincome-prod/pull/303
