### ISSUE TITLE
[Admin Tool Feature]: Randomizer Prototype

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#346]
**Feature** 
Recipients can be selected truly randomly. 

**Describe the solution/feature**
An admin user of Social Income can randomly select a specific amount of new recipients from the waiting list.

**Additional context**
This issue consist of a working prototype that includes the GitHub setup to publish the selection. Out of scope: adding the feature in the admin tool (separate issue will be created)

**Comment by ssandino** [comment]
Moving it to the April sprint

**Comment by Dariusz385** [comment]
Please

**Comment by ssandino** [comment]
We are way beyond prototype
