### ISSUE TITLE
[Survey] Welcome message

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#364]
- write content (2 languages)

**Comment by andrashee** [comment]
Do you have those already for the different surveys? If yes, could you send me texts?

**Comment by ssandino** [comment]
What about a generic message for all surveys: 

Hello XY, 
Thank you for taking the time to complete the short survey. Your responses will help us understand the impact of Social Income and identify areas for improvement.

Halo XY,
Wi tɛl una tɛnki fɔ we una tek yu tɛm fɔ dɔn di shɔt sɔv. Yu ansa dɛn go ɛp wi fɔ ɔndastand di impak we Sɔshial Inkam gɛt ɛn fɔ no di say dɛn we wi fɔ impɔtant.

**Alternative:** 
If you think it would be better if we state which survey it is, then we could amend the first sentence in the following way: 
Thank you for taking the time to complete the _onboarding/regular/offboarding/continuous_ survey.
