### ISSUE TITLE
[Mobile App Feature]: Implement new Account Page 

### ISSUE THREAD

**Issue by novas1r1** [socialincome-san/public#387]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Criteria for Completion

- [x] fetch organization data from firebase
- [x] add new field paymentProvider to recipient
- [x] add new field selectedLanguage to recipient
- [x] fetch all data from firestore
- [x] update data to firestore on changing any field
- [x] add logout possibility
- [x] add hint for deleting the account by contacting the support
- [x] add support to design
- [x] V2: fix input fields design to match the original one (custom textformfield needed in case we want to do it)
- [x] V2: change app language if it's changed in the profile

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
The contact information for the recommending organisation seems not yet linked. I should say Org. Name + respective Contact Name and number in database. If database has no contact name, then it can just be empty (or without the two lines). This is anyway an exception as we always have a contact. 

![IMG_0958](https://user-images.githubusercontent.com/6095849/236661163-8c97d916-a7b1-437f-9bbb-ba5fb0ed4576.jpeg)

**Comment by novas1r1** [comment]
This is done already. Organization data has to be filled to be visible.
