### ISSUE TITLE
[survey] Main Setup for Standalone Survey Tool

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#39]
### Problem

Currently we use the third-party tool [Typeform](https://www.typeform.com) for the recipients surveys. This setup has considerable drawbacks: costs ($800+ per year), data in US, flexibility, no multi-language, managing surveys for recipients (knowing who filled out what) and less privacy etc.

### Solution

**Standalone solution**
- based on a react app in a separate top-level folder in the repo (surveys/...)
- connected to the (new) tailwind components (for the moment we would use button and text field component)
- all answers saved directly in our Firebase DB in separate collection without any personal data (except a unique identifier, which does not allow for conclusions to real person), so it can be better analysed and used for real-time insights, similar to our [financial transparency](https://socialincome.org/finances))
- surveys are accessible via subdomain (surveys.socialincome.org/...)

What could be a good unique identifier for the surveys (also used in the URL to access it)?

> (from @andrashee) I think I would prefer if we generate for each recipient a secure token, add this to the recipient document as an attribute (e.g. survey_token), and then use that one instead of directly the UUID. We could then design the firestore rules that one can read/write a survey document with survey_token id, if there exists a recipient with the given survey_token.
> 
> Another approach would be to use proper jwt tokens using the auth module in firebase. https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk.
> We can create the token when generating the survey links. The token contains the recipient's uuid. The react app can then call the auth endpoint firebase.auth().signInWithCustomToken(token). Once authenticated it can query the survey collection. In the request, the token is passed along and one can read the recipient's uuid in the security rules. I would go for this approach since jwt token authentication is a standard and widely used.

How would user XY with `survey_token`=`S5bTLl2ZVeccOPJcJ788`  access a survey:

[surveys.socialincome.org/S5bTLl2ZVeccOPJcJ788/](surveys.socialincome.org/S5bTLl2ZVeccOPJcJ788/) -> overview of all surveys for XY
[surveys.socialincome.org/S5bTLl2ZVeccOPJcJ788/onboarding](surveys.socialincome.org/S5bTLl2ZVeccOPJcJ788/onboarding) -> onboarding survey for XY

**Remember:** Recipients don't have a login. So the `survey_token` should make sure that a) we know who filled it out, b) can connect the recurring survey answers to one user (measuring poverty level over time) and c) have a bit of security from someone randomly filling out or accessing surveys (i.e. when we use sequential numbering and it's easily guessable) and d) provide a way to manage recipients surveys.

**Other information:** each recipients gets approx. 8 surveys over the 3 years. In the best case, recipients get the survey in their main language (often not English), so multi-language should be thought into it (but it's different from the routing of the website, where we have to guess based on IP or browser language or cookie. We know who is accessing the survey (thanks to the `UID`) we could easily serve the right language based on the recipients `main language` field. As a start it could also be only English (as it is now, until the discussion [here](https://github.com/socialincome-san/public/discussions/57) found its decision.

___

This issue includes information and inputs from the [discussion](https://github.com/socialincome-san/public/discussions/94) about the standalone survey app.

**Comment by Anup11dwivedi** [comment]
Hi

**Comment by ssandino** [comment]
Future steps (copied from Slack):

> Sure, I'll definitely connect with him. If we can have one small technical session that will be helpful.

Easiest if you connect directly @renestalder @Anup11dwivedi

**Comment by ssandino** [comment]
Screen Designs:
![](https://user-images.githubusercontent.com/6095849/192386059-3ab0d3bf-30e5-4501-bea1-10f820d0489f.jpg)

**Comment by ssandino** [comment]
@Anup11dwivedi this might help: 

- For the language dropdown you can use this [ready-to-use dropdown button ](https://socialincome-san.github.io/public/?path=/story/components-combobox-combobox--standard)
- For the normal white buttons you have this one [here](https://socialincome-san.github.io/public/?path=/story/components-button-button--tertiary)

Form fields are also coming, as well as the segmented controls.
@renestalder added the segmented controls to end of the components google doc

**Comment by renestalder** [comment]
For all components, you are missing in our UI library by now, I recommend using the most appropriate standard, native HTML element for now, unstyled. Like if you are blocked for the test form fields not being ready in the UI library, use `<input>` directly for now. You'll find those elements later in the UI and should be able to easily copy/paste/replace your current solution as soon as they are available.

**Comment by ssandino** [comment]
I think @renestalder was referring to this tag, which prevents search engines from indexing the page: 
`<META NAME="robots" CONTENT="noindex">` ([Source](https://blog.hubspot.com/marketing/how-to-unindex-pages-from-search-engines#:~:text=Add%20both%20a%20%22noindex%22%20and,the%20links%20on%20that%20page.))

**Comment by ssandino** [comment]
The two surveys to rebuild with the new tool. You can copy paste all text parts from there: 

1. Initial (every new recipient fills it out 1 time): https://digitaleschweiz.typeform.com/to/WXgFXy8M
2. Recurring (recipients fill it out every 6 month): https://digitaleschweiz.typeform.com/to/PwxHI4zU

**Comment by ssandino** [comment]
Reassigning – requirement might have changed.

**Comment by ssandino** [comment]
This was a very generic issue – the main setup is meanwhile done. Therefore I close this issue. There are some further requirements in this issue about management of the surveys for the users. However, this is not a priority (and could be added later in a new issue)
