### ISSUE TITLE
[Mobile App Feature]: New Signup / Login Process

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#415]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The current signup and login process has some usability issues: 

- continue button is hidden in iOS after number field is filled out
- floating label for number field is broken

### Describe the solution/feature

Adding the newly designed signup / login process:
<img width="688" alt="Screenshot 2023-05-08 at 10 43 53" src="https://user-images.githubusercontent.com/6095849/236778648-e0775f3d-089c-4e09-8468-48a52b0ebebd.png">

### Describe alternatives you've considered

none

### Anything else?

Screenshots: 

Floating Label
<img width="600" alt="Screenshot 2023-05-08 at 10 45 33" src="https://user-images.githubusercontent.com/6095849/236779036-dd48bc5d-6af7-4007-b7a7-dc80dd334f90.png">

Hidden "Continue" button (and no way to do it on the keyboard)
<img width="148" alt="Screenshot 2023-05-08 at 11 14 59" src="https://user-images.githubusercontent.com/6095849/236785974-5f62c5df-813e-48e0-ac85-97761aa4c2e7.png">

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
Here the animation as a gif (let me know if you need it as movie).

1000px
![mundo-loop](https://github.com/socialincome-san/public/assets/6095849/365034a4-a20f-487f-b1c0-421c68571ef5)

500px
![mundo-loop-500](https://github.com/socialincome-san/public/assets/6095849/5befbf48-0504-4c4f-888d-0f00776720c4)

**Comment by novas1r1** [comment]
@MDikkii this is finished already, isnt it? Or is there something missing?

**Comment by MDikkii** [comment]
Custom snackbar / alert is missing, plus not sure about error messages, maybe it would be better to make them more straight forward as for now we just show what came from firebase sdk

**Comment by novas1r1** [comment]
For the error messages - especially firebase - I added a separate ticket.

**Comment by MDikkii** [comment]
So UI should be done 🎉
