### ISSUE TITLE
[Mobile App Feature]: Unified Alert / Toast 

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#416]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

There is a unexpected alert/toast in the login process on the bottom, unstyled and with a firebase code (see screenshot)

### Describe the solution/feature

Unifying the alerts/toasts as planned in the design. Example (with unrelated text):

<img width="381" alt="Screenshot 2023-05-08 at 11 22 33" src="https://user-images.githubusercontent.com/6095849/236787498-cdbce1d6-75f1-4282-b053-90834638a003.png">

### Describe alternatives you've considered

none

### Criteria for Completion

- try to login, but fail the captcha a few times

### Anything else?

![IMG_0964](https://user-images.githubusercontent.com/6095849/236787252-c0af76f8-8221-4f36-8156-4e1b7559d176.jpeg)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by novas1r1** [comment]
Success:
<img width="345" alt="image" src="https://github.com/socialincome-san/public/assets/2575205/a85759da-edbb-4a3d-83ab-2a220c361d7a">

Warning:
<img width="345" alt="image" src="https://github.com/socialincome-san/public/assets/2575205/9098d244-80f2-4117-8d7a-4c77ae3dfae6">

Error:
<img width="345" alt="image" src="https://github.com/socialincome-san/public/assets/2575205/c64eee84-5e3e-47b6-ab61-3bafc163b0e9">

Info:
<img width="345" alt="image" src="https://github.com/socialincome-san/public/assets/2575205/f7a013ca-0009-4ad4-a9e3-54380b4c118c">
