### ISSUE TITLE
[Mobile App Feature]: Widget to confirm number (contact # = payment #)

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#417]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When onboarding new recipients we only know the number of the `contact phone`, but not yet the `payment phone`. In most cases it is the same, but not always. If a designated recipient downloads the app and uses the app for the first time, it should see a widget asking: 

<img width="360" alt="Screenshot 2023-05-08 at 17 22 53" src="https://user-images.githubusercontent.com/6095849/236864888-2abd8930-397f-452d-ab89-14b1c6486c4b.png">

If the user clicks `YES`
<img width="513" alt="Screenshot 2023-05-08 at 17 23 11" src="https://user-images.githubusercontent.com/6095849/236864977-cd1cc5fb-0ba5-4166-a832-8cf55db5d3d4.png">

If the user clicks `NO`, the user is forwarded to the profile page, where the `payment phone` is highlighted red (cause it's mandatory but missing. There he has to fill in the `payment phone`. 

As long as there is no `payment phone` filled in the widget appears in the stream of the landing page. 

### Describe the solution/feature

see above

### Describe alternatives you've considered

none

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by novas1r1** [comment]
Is this still relevant? We have it the other way around - it asks you if your contact phone number is the same as the payment phone number since we use the payment phone number for the login.

**Comment by ssandino** [comment]
There is some cases where we only have a contact phone number (for example: a recipients gets a mobile payment account, so to say a new payment number, after they get selected). But this seems to be special case. As we solved the main issue we tried to solve: certainty that we know both phone numbers of a user, I close the issue.
