### ISSUE TITLE
[Mobile App Feature]: Replace old implementation of SplashScreen

### ISSUE THREAD

**Issue by novas1r1** [socialincome-san/public#440]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

"A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps."

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by MDikkii** [comment]
resolved with https://github.com/socialincome-san/public/pull/544
