### ISSUE TITLE
[Mobile App Feature]: Write user into "updated by" field in payment collection

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#456]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When a recipient uses the mobile app to confirm or contest a payment, it currently doesn't update the field "Last updated by" in the payment collection. This information would help us to see who confirmed (us or them) and add some traceability on changes. 

### Describe the solution/feature

Writing recipients `First Name` and `Last Name` into the field

### Anything else?

<img width="1196" alt="Screenshot 2023-04-27 at 23 50 23" src="https://github.com/socialincome-san/public/assets/6095849/010c7a01-5cb6-4782-ba59-a3380ae0c1be">

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by novas1r1** [comment]
I added the lastUpdatedAt and set it to the current timestamp and also added the first and lastname of the user who triggers the confirmation or contest from the app.
