### ISSUE TITLE
[Admin Tool Bug]: SVG Logo not shown after refresh of page

### ISSUE THREAD

**Issue by Matthabbey** [socialincome-san/public#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The logo.svg is not found after a reload of the page

### Steps To Reproduce

1. Go to '[admin.socialincome.org](http://admin.socialincome.org/)'
2. Login
3. Go into a collection
4. Do a page reload

### Expected Behavior

[Show more
](url)

### Screenshots?

![](https://user-images.githubusercontent.com/6095849/220927743-107111ca-3fa0-41dd-a7cb-866a5b6929e2.png)

### Desktop Environment (please complete the following information)

```markdown
- OS: Mac
- Browser: Safari (but also others)
- Version:
```

### Smartphone Type (please complete the following information)

```markdown
- Device:
- OS: Safari
- Browser:
- Version:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by socialincome-dev** [comment]
Updated this one with a screenshot and assigned it to you @Matthabbey (not sure why you made a copy of issue [#329](https://github.com/socialincome-san/public/issues/329), which we closed now)
