### ISSUE TITLE
[BUG]: Currency Visual Issue for Payment Card

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

SLL is messing up the payment card

### Desktop Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Version:
```

### Smartphone Type (please complete the following information)

```markdown
- Device:
- OS:
- Browser:
- Version:
```

### Additional context

![image](https://github.com/socialincome-san/public/assets/6095849/4477da00-ffce-4c17-ad79-4638b4ee1fa2)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by MDikkii** [comment]
closed with #460
