### ISSUE TITLE
[Website Feature]: Change Logo

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#497]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We changed our logo and it has to be replaced on the [upcoming website](https://prod.socialincome.org)

Instead of this: 
![Screenshot 2023-08-12 at 12 14 21](https://github.com/socialincome-san/public/assets/6095849/ae06b4f2-0847-4840-9f72-b0a0e0b9a77a)

It should newly be this (the bars are slightly more tilted):
![Logo-Social-Income-RGB-Yellow](https://github.com/socialincome-san/public/assets/6095849/88a7c740-905a-463b-b0a6-c2d3cb2fdaee)

### Describe the solution/feature

Replace the file/path

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by DarkMenacer** [comment]
So I’ve replaced the file with the new one. The new logo now appears in the sidebar. But even the logo on the login/signup page has changed and the new logo there (attaching the s
<img width="615" alt="Screenshot 2023-08-13 at 13 51 25" src="https://github.com/socialincome-san/public/assets/81011730/2c7c305a-9523-41fb-8d43-a8ce0e6354ed">
creenshot) doesn’t feel like that is how it is intended. Hence I thought I should confirm it once before creating a PR.

**Comment by DarkMenacer** [comment]
I”m done updating the logo on my system.
Now I tried creating a branch (pranav/change-logo) and pushing to the branch but it seems that I don’t have sufficient permissions for that. (Attached screenshot).
<img width="683" alt="Screenshot 2023-08-13 at 13 35 41" src="https://github.com/socialincome-san/public/assets/81011730/2987b03f-394d-46b7-a566-edc4cf29c6cb">

So instead I forked the repo, made the branch and pushed to that branch. Now to create the PR I was wondering what my target branch should be. Can you let me know which branch I should create a PR on? I apologize if this is mentioned somewhere in the repo.

**Comment by DarkMenacer** [comment]
Created a PR: https://github.com/socialincome-san/public/pull/498

**Comment by DarkMenacer** [comment]
PR merged into main
