### ISSUE TITLE
[Website Feature]: Change Favicon

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#507]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The draft website (staging / prod) has currently an outdated version of the Social Income Icon as favicon. 

Current favicon: 
![Screenshot 2023-08-14 at 23 13 44](https://github.com/socialincome-san/public/assets/6095849/fcc41227-661c-4937-9d74-1656c6a79e26)

We should replace it with the new icon:
![Screenshot 2023-08-14 at 23 15 13](https://github.com/socialincome-san/public/assets/6095849/9e8d1a4e-a4ff-463a-a8e7-fe9f0f566149)

### Describe the solution/feature

1. Clone Repo
2. Unzip the file
[favicon.ico.zip](https://github.com/socialincome-san/public/files/12339581/favicon.ico.zip)
3. Replace current favicon (path: public/website/public/favicon.ico)
4. Commit and make new PR

### Describe alternatives you've considered

none

### Criteria for Completion

New favicon should be shown

### Anything else?

This task is especially made for a first contribution.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
Please go for it @nueladeyemi1 - thanks!

**Comment by nueladeyemi1** [comment]
Thank you @ssandino

I changed it and made a PR, thanks!
