### ISSUE TITLE
[Website Feature]: Migrate Footer

### ISSUE THREAD

**Issue by mkue** [socialincome-san/public#518]
## Goal

Migrate footer from https://socialincome.org to new website.

## Tasks

- Finish new Footer component
  - Include GitHub repository link
- Make sure it looks good on all display sizes

## Go to know

- Use [Heroicons](https://heroicons.com) and [react-simple-icons](https://github.com/icons-pack/react-simple-icons) (both packages are already installed)
- Use Tailwind classes for the styling/positioning 
  - Help for making it responsive/mobile friendly: https://tailwindcss.com/docs/responsive-design

**Comment by anthonyray** [comment]
Started working on this!
