### ISSUE TITLE
Automate PDF creation for confirmation of donations (for tax declaration)

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#52]
**Is your feature request related to a problem? Please describe.**
We currently create the yearly confirmation of donations (for tax purposes) manually for each contributor (in Switzerland). Immense work! 

**Describe the solution/feature**

**Automate yearly confirmation of donations by:** 

**The issue can be split up in 3 parts:**
- [x] Part 1 PDF tool
- [x] Part 2 Calculating
- [ ] Part 3 User Flow 

**Part 1 PDF tool**
- choosing the best pdf tool (like [PDFmake](http://pdfmake.org/#/features), [PDFkit](https://github.com/foliojs/pdfkit/tree/3f69586f3cb9d46cb58f255920863bbcbc5f2acd) ... or others)
-  using the assets ([Unica77 font and logo](https://github.com/socialincome-san/public/tree/main/shared/assets))
- doing the basic layout in the two languages ([template](https://docs.google.com/document/d/1AA405WEDqHniSRK6KfQb7-oqixUDIjr6PqFqV7Z_TB4/edit?usp=sharing))
- generating the PDF assuming all variables being computed ... e.g. `const generatePDF = ({firstName: string, ...}) => string`

**Part 2 Calculating**
- Calculating the total amount of donations by a contributor (which has country CH and pays through Stripe) directly in the system 
- IF currency is not CHF, it has to be changed to CHF with the exchange rate API (either Jan 1, or for each at the time of donation). Note that we have the exchange rate of every day saved in a collection in our FB. 
- This should be passed on to a PDF maker
- The PDF maker generates a PDF and includes also the address and birth date of contributor in the 
- UPDATE: List of all single payments on the second page could be nice to have

**Part 3 User Flow**
- Most likely three separate text links in the user dashboard that generate the confirmation of donation in the desired language (DE, FR, IT, EN) -> There is not yet a translation for the IT and EN
- First it would check if all data (name, address, birthdate, donations in respective year) is available.
- If not: return a message if not, so user can complete it in his dashboard.  
- If yes: a pdf is generated and opened in a new window or downloaded or saved in firebase (if possible)

(best would be to run it in real time, so user can also change his information ... then run it again)

**Describe alternatives you've considered**
Manually creating the files. Not scalable.

**Comment by Ilikepizza2** [comment]
Ok woah this is somewhat a big issue!
Let me clear some of the work I have in other repos and then I'll get to work.

**Comment by ssandino** [comment]
Fantastic! Thank you @Ilikepizza2. Part 1 would be already a huge leap forward. I added above also the link to the templates.

**Comment by Ilikepizza2** [comment]
Hello there!
I scouted the codebase, getting to know the code and I am sorry to say but most probably this is an issue far beyond my current capabilities. I'd probably waste much of your time and still I might not be able to complete the issue. So, I'm unassigning myself. I'll come back to work on this project once I gain some experience. Sorry to disappoint... hope to see this project grow.
Thanks!

**Comment by ssandino** [comment]
@Ilikepizza2 Thanks for letting us know! All good ... we hope to see you coming back in the future

**Comment by ssandino** [comment]
@Ilikepizza2 Thanks for letting us know! All good ... we hope to see you coming back in the future

**Comment by ssandino** [comment]
Closing this issue (Part 3 I added as a separate issue #259, as it depends on the new website with the new dashboard for contributors)
