### ISSUE TITLE
Update Readme with profiles of code contributors

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#55]
**Goal:** 
Display the GitHub contributors right in our Readme to create a strong(er) sense of community. 

Good example: [Read me of Contributor Covenant](https://github.com/EthicalSource/contributor_covenant/blob/release/README.md) and their embedded [SVG](https://opencollective.com/contributor-covenant/contributors.svg?width=890&button=false)

**Why is it a good example?** 

- It scales nicely
- profile images are sharp, round and small
- it can be embedded and therefore done with the straightforward markdown language

There are many tools doing it (like [this](https://github.com/dummy-crew/svg-contributors)). Open questions: which one to implement, how to automatically save the SVG on our own server (as it could also be used on our website) and how do new contributors over GitHub appear automatically?

So visually it should be exactly like [this](https://github.com/EthicalSource/contributor_covenant/blob/release/README.md) (small circles).

**Comment by daksh10110** [comment]
Hey I can do this, can you assign this task to me.

**Comment by Yatharth-Jain** [comment]
Hey There, I would like to Contribute in this Task. Along with that this is my first Open Source step so also want some guidance. So can you assign that task to me and guide me on any issue

**Comment by ssandino** [comment]
> Hey I can do this, can you assign this task to me.

how is it going @daksh10110 – anything we can help?

**Comment by daksh10110** [comment]
I am extremely sorry for not informing before, I had a lot of work lately so I wasn't able to do this task.

I have my exams from the next week so it would take some time, you can assign it to some other person if you wish to.

The idea I had in mind was to get the photos using GitHub api and then using flask and pillow to send the files from there.

**Comment by ssandino** [comment]
Thanks for the quick answer and sharing your approach. Hope your exams went well. I also assign @Yatharth-Jain in case he is still interested and wants to push this issue forward. Then we see how to wrap it up.

**Comment by ssandino** [comment]
If we make this feature more versatile, we open up a new issue
