### ISSUE TITLE
[Website Feature]: Draws overview page

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#562]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We currently don't show any verifiable information about the drafts (selection of recipients)

### Describe the solution/feature

As discussed with @CluEleSsUK, a basic start could be something like this: 

<img width="609" alt="Screenshot 2023-09-04 at 15 45 34" src="https://github.com/socialincome-san/public/assets/6095849/9b023a2e-7a03-4483-b36e-2bb8f17cf54c">

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
Input from @mkue to keep it simple for you:
For the future draws section, we can just hardcode the information for the launch of the website next week.

For now the information is:
_15.10.2023, Aurora Draw, 10/400

We can always add more "intelligence" later on, where we add future draws in the admin tool and they are shown automatically when the date is in the future. But for now it might be a overkill. What you think?

**Comment by CluEleSsUK** [comment]
I think this makes a lot of sense for future draws; for past draws I think it would still be great to pull from the repo so it 'follows the trail' so to speak.

**Comment by ssandino** [comment]
Yes, past draws should "follow the trail"

**Comment by mkue** [comment]
> I think this makes a lot of sense for future draws; for past draws I think it would still be great to pull from the repo so it 'follows the trail' so to speak.

I agree. For past draws, we should link to the file on GitHub and maybe also display its content more nicely on the website.
