### ISSUE TITLE
[Admin Tool Feature]: Adding questionnaire type to overview

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#579]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It's difficult for field workers to see which questionnaire they are sending to the recipients, as in the `Upcoming survey` view ([link](https://staging-admin.socialincome.org/upcoming-surveys)) the information is not shown. 
<img width="1885" alt="Screenshot 2023-10-05 at 11 50 44" src="https://github.com/socialincome-san/public/assets/6095849/41077655-9a17-4c2d-93bd-534716beb944">

### Describe the solution/feature

Adding the 

The column already exists in the `Survey` overview view ([link](https://staging-admin.socialincome.org/c/surveys))

<img width="204" alt="Screenshot 2023-10-05 at 11 51 24" src="https://github.com/socialincome-san/public/assets/6095849/a151ea09-38b9-469e-aac6-73802c4194f4">

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by micharied** [comment]
I would like to work on this issue. :)

**Comment by micharied** [comment]
opened pr - https://github.com/socialincome-san/public/pull/709

**Comment by ssandino** [comment]
Great job, @micharied 

As your PR is reviewed and merged into the main branch, the issue can be closed. It's not mandatory, but it can be helpful if you link the branch with the issue, as merging a pull request may automatically close the associated issue. This way, you won't have to do it manually.


<img width="356" alt="Screenshot 2024-01-26 at 16 58 01" src="https://github.com/socialincome-san/public/assets/6095849/9bd348aa-5766-4b4f-8305-19eb773367e0">
