### ISSUE TITLE
[Mobile] Update Dart to support null safety

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#60]
_Transfer from previous app repo_

Written by @MDikkii:
Dart from version 2.12 support null safety and null safety operators. In my opinion, it is beneficial to update to null safety features. Not only we gain more control over our code and how it should behave, it will reduce number of NullPointerExceptions. Also we should be able to make future language updates easier as null safety seems to be the most braking change in recent versions of Dart.

Some references on null safety and how to migrate:
https://dart.dev/null-safety
https://dart.dev/null-safety/migration-guide

It will require changes in most of our code files, so I wanted to check if all of current and future contributors will be happy with this update.

What do you think?

**Comment by MDikkii** [comment]
Solved with https://github.com/socialincome-san/public/pull/82
