### ISSUE TITLE
[Mobile App Feature]: Enable push notifications for Android

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#61]
**Describe the solution/feature**
One of the main goal of the app is to get timely feedback from the recipients (i.e. confirmation on payments) and relies on notifications to get their attention. Therefore the feature of push notification should be developed.

**Comment by ssandino** [comment]
A example for a notification for the app users would be this month: 
_"Due to inflation we are raising the monthly Social Income from SLE 500 to SLE 700."_

How would we manage @MDikkii such input? Would we need a specific filtered recipient table for only app users in the admin tool?

**Comment by novas1r1** [comment]
Currently blocked on iOS because we can't register org.socialincome.app.stage. @MDikkii wrote apple already to give us access to this bundle id.

**Comment by novas1r1** [comment]
I splitted this up in two separate tickets.
