### ISSUE TITLE
[Mobile] Registering app with new name on Play Store

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#62]
**Describe the solution/feature**
Registering the app with new name org. instead of com.

- [x] store listing
- [x] basic configuration
- [x] provide new app bundle
- [x] adding it to Play Store

**Comment by MDikkii** [comment]
App in beta channel, still in review.

**Comment by MDikkii** [comment]
Reviewed, you can check current version on early access from play store https://play.google.com/store/apps/details?id=org.socialincome.app

**Comment by ssandino** [comment]
Nice! This works ...
