### ISSUE TITLE
[Mobile App Bug]: Violation of playstore policy

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Violation: App must target Android 13 (API level 33) or higher

To ensure that you can continue to make updates to your app you must:

- Update your app to target Android 13 (API level 33) or higher.
- Publish a new version of your app to production. Before you do this, you can test your app using internal, closed, or open testing.

[More about the issue](https://play.google.com/console/u/0/developers/6131634535900286537/app/4975166784260387460/policy-center/issues/4985965730546804811/details)

<img width="896" alt="Screenshot 2023-11-14 at 22 40 42" src="https://github.com/socialincome-san/public/assets/6095849/55bd5e70-4cc9-4cde-ab56-517f826aa030">

### Desktop Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Version:
```

### Smartphone Type (please complete the following information)

```markdown
- Device:
- OS:
- Browser:
- Version:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
Might have been fixed with the appeal.

**Comment by KarinBerg** [comment]
Fixed with https://github.com/socialincome-san/public/issues/861
