### ISSUE TITLE
[Mobile App Feature]: Adding multi language capability

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#63]
**Is your feature request related to a problem? Please describe.**
The app currently only allows for one language (EN). As a lot of recipients don't speak English, we would have to add an additional language Krio.

**Describe the solution/feature**
This issue covers the technical part of adding the capability to have a multi-language app and respective language files. (not the translations)

**Comment by ssandino** [comment]
see also discussion **#57 Localization & Translations**

@MDikkii is any of those tools mentioned ([i18next.com](https://www.i18next.com/), [localizely.com](https://localizely.com/blog/nextjs-i18n-tutorial/), [locize.com](https://locize.com/blog/next-i18next/), [crowdin.com](https://crowdin.com/)) better suitable for the app? Goal is to use one tool that combines all translations, so your input in the discussion could help selecting the right one.

**Comment by novas1r1** [comment]
I think we should discuss this the next days and then go with the best solution which matches our needs.

**Comment by MDikkii** [comment]
you can check my wip on `mdikkii/63-localization-next-18i`

**Comment by novas1r1** [comment]
I checked the package and talked to Michael. It seems to be quite uncommon and hasn't been updated for 9 months. It's still using the old dart version and this could lead to some dependency issues in the future. Also it doesn't bring any benefit and is not sharing resources with the webapp so I would suggest to go the standard flutter localization way to be safe in the future and prevent the risks. Wdyt @MDikkii ?

**Comment by MDikkii** [comment]
Is there "standard" way? 😀 I was trying to check localisation before and everybody has different way of doing it. But sure, if you think that it is not needed to be done with i18next we can make it manually.

Let's discuss what is standard way on dev weekend then.

We still need to add new custom country somehow, but I believe it will be similar to what I was trying to do with this KrioDelegate

**Comment by MDikkii** [comment]
We have added Krio and English for now.
