### ISSUE TITLE
[Mobile App Feature]:  Autofill security codes from SMS Messages

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#66]
**Describe the solution/feature**
The text messages (SMS) from Google Auth with the security codes should be autofilled into the respective code field. Might work out of the box for some phones with newer software. This issue is more to check, if one must do something specifically that it works everywhere (Android, iOS).

**Comment by YashGupta1510** [comment]
I used this method in one of my apps.
Both android and ios allow you to read the messages, so what I did was that I stored that text part in a temporary string and extracted the auth code using basic string functions like split. Lame method but works for me.

**Comment by ssandino** [comment]
@MDikkii some input from the open source community

**Comment by MDikkii** [comment]
@YashGupta1510 thanks for comment 🎉  Do you recall that you read all of user messages (like... getting the `READ_SMS` permission on Android was required) and try to get the one with OTP token? Or did you do that with some other way of getting OTP codes?

**Comment by YashGupta1510** [comment]
I used the Telephony package(available for both android and ios) from pub.dev and read any new notification that came after I come on the OTP filling page/State.
