### ISSUE TITLE
[Mobile App Bug]: Account page override profile data changes

### ISSUE THREAD

**Issue by MDikkii** [socialincome-san/public#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The account page does not use the most recent profile data. It can lead to an override of already updated fields when the user tries to update more than one field on the profile. 
Please also check if account page is updated between going for the first time to the screen, changing data and coming back to the screen later on.

It can be related again to `update` vs `set` firebase methods.

### Steps To Reproduce

1. Go to Account page
2. Change Last name, click ✅ 
3. See updated profile message 
4. Change First name
5. Observe that the Last name is set to old one in firebase console again
6. Go back to dashboard
7. Enter profile again - observe the data on the screen and in firebase console

### Expected Behavior

Account screen always show latest user profile
Account screen does not override previously made changes to the user profile 

### Desktop Environment (please complete the following information)

```markdown
- OS: -
- Browser: - 
- Version: -
```

### Smartphone Type (please complete the following information)

```markdown
- Device: Xiaomi Mi10T
- OS: Android 12
- Browser: -
- Version: 1.1.10
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by MDikkii** [comment]
I still can see it. Maybe my repro steps are not the best. Please check the video 

https://github.com/socialincome-san/public/assets/6149761/b0f91382-3bc1-460a-9eb8-0169302caac2

**Comment by ssandino** [comment]
Yes, now I can reproduce it (I was missing the going back to the overview, Step 6).
