### ISSUE TITLE
[Admin Tool Feature]: Get rid of number validation

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#684]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Our system currently restricts input to only Sierra Leonean phone numbers. This was initially implemented to prevent NGOs from entering incorrect numbers (such as those missing prefixes). However, NGOs no longer have access to the admin tool, making this restriction unnecessary. Additionally, this limitation complicates testing since most of our test numbers are not from Sierra Leone, requiring manual changes directly in Firestore.

### Describe the solution/feature

Remove the restriction that checks and allows only Sierra Leonean phone numbers. This change will facilitate easier and more efficient testing with diverse phone numbers.

Validation is done here [recipients properties](https://github.com/socialincome-san/public/blob/main/admin/src/collections/recipients/RecipientsProperties.ts#L89)

### Anything else?

<img width="721" alt="Screenshot 2023-12-21 at 10 10 10" src="https://github.com/socialincome-san/public/assets/6095849/c676925c-bcb9-479f-8c47-aa954c8da20d">

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by micharied** [comment]
Hello, 
I would like to contribute to this project and looked at this issue as a start. Should there be no validation at all or should there be a validation for the length of the number? 
Greetings Micha

**Comment by ssandino** [comment]
Hi @micharied – great, this is actually a good issue to start with! 

The validation is done in `RecipientsProperties.ts`. Removing the validation would already fulfill the issue's goal. 

Your question about adding another validation is totally valid. You can of course add a validation, such as limiting the digits to 15 – this is recommended by the ITU ([E.164](https://en.wikipedia.org/wiki/E.164)). The [minimum length](https://stackoverflow.com/questions/14894899/what-is-the-minimum-length-of-a-valid-international-phone-number) of a valid international phone number is not straightforward, and as such, not validating this seems to be the best approach.

I've assigned this task to you. Please let us know if you need any help along the way. Also, if you notice any steps that haven't been documented for new contributors in the README, thanks for updating it!

**Comment by ssandino** [comment]
Great job, @micharied. I close the issue.

The comment of @mkue in the PR #706 I added as new issue [#719](https://github.com/socialincome-san/public/issues/719). However, this change might have some effects on the mobile app and must first be discussed.
