### ISSUE TITLE
[Admin Tool Feature]: Download survey data as CSV

### ISSUE THREAD

**Issue by mkue** [socialincome-san/public#717]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Describe the solution/feature

Add option to download completed survey data in one or multiple CSV files.

**Comment by ssandino** [comment]
I guess this is a duplicate of issue #710

**Comment by mkue** [comment]
I don't think so. Or, I don't think the FireCMS download option will give a usable CSV file. This is a bit tricky because the data from the different questionnaires is different as well.
