### ISSUE TITLE
[Website Feature]: Video pages with dedicated URLs

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#718]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We currently do not have a dedicated URL for our videos. While they are embedded on our website, there are instances in our communications where we need to directly link to a specific video. 

At present, we have to link to Vimeo for this purpose, but doing so results in lost website traffic.

### Describe the solution/feature

Hence, creating specific pages for our videos would be beneficial. To ensure scalability for future additions, it would be practical to introduce an extra level in the folder structure, using '(video)' which is ignored, but helps to keep all video files together. 

Page URLs: 
`socialincome.org/testimonials-video `(for the filmed movie)
`socialincome.org/explainer-video` (for the illustrated movie)
`socialincome.org/money-flow-video` (for the illustrated movie)
Routing: (video)/recipients-view

On the page, the video should be embedded as large as possible, with only a small margin surrounding it.

Out of scope: Creating an overview page of all videos at socialincome.org/video is currently out of scope and not needed.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by micharied** [comment]
I will work on it :)

**Comment by micharied** [comment]
Should the navigation still be visible?

**Comment by ssandino** [comment]
Thx! Yes the navigation should still be visible
