### ISSUE TITLE
[Functions Feature]: Add Firebase function that sends email to new contributors after first payout

### ISSUE THREAD

**Issue by mkue** [socialincome-san/public#726]
We had a Firebase function in the old code repository that sent out an email to new contributors after the first payout to recipients happened, i.e. on the first 16th of a month after their initial donation.

The function is located [here](https://github.com/socialincome-san/soincome-prod/blob/master/functions/etl/first-payout-email.js).

The goal of this issue is to have this functionality back. The email template should be a Handlebars template (see `shared/templates` directory), and the email should be sent out via the `sendEmail()` function.

**Comment by ssandino** [comment]
Just saw that [MJML](https://github.com/orgs/socialincome-san/discussions/174#discussioncomment-4203012), which we use already for the certificate emails, had a [new release yesterday](https://github.com/mjmlio/mjml/releases/tag/v4.15.0) fixing some issues. Might be a good moment to update.

**Comment by mkue** [comment]
@ssandino, let me know when you have updated the email template, and provide me the expected template data. then i'll update the code and make sure the function is enabled.

do you know how we will handle multiple languages? can that be done in a single template? or do we have two templates?

**Comment by ssandino** [comment]
Great. Working on it. I assume language specific templates are easier to handle. Otherwise we need to have variables for every text part and save it in our `shared lang folder`. And each text variable (i.e. paragraph) can have a nested variables (i.e. fname) – it seems to become a bit too complex/nested.

**Comment by mkue** [comment]
I don't think we will ever need to store any text that goes into the email templates in our code base. This is why I partly also want to  use the templates on Sendgrid. We just pass variables like names, numbers, etc. to the template, everything else, e.g., the text, can directly be edited on Sendgrid.

**Comment by mkue** [comment]
It seems though that Sendgrid does not support multi-language templates. So, the easiest is to just have multiple templates on Sendgrid for the same payout mail (e.g. first payout email) – one in each language. I guess, currently, that would be one template in English and one in German.

**Comment by mkue** [comment]
What's the state of the email template? Did you have time to work on it @ssandino?

**Comment by ssandino** [comment]
Added the two `first payout emails` to sendgrid:
EN Version: [4e616d721b0240509f468c1e5ff22e6d](https://mc.sendgrid.com/dynamic-templates/d-4e616d721b0240509f468c1e5ff22e6d/version/7de4fce4-8ba0-4dfa-a099-bb706d846cf6/editor)
DE Version: [4e616d721b0240509f468c1e5ff22e6d](https://mc.sendgrid.com/dynamic-templates/d-4e616d721b0240509f468c1e5ff22e6d/version/3cbc181b-5a0e-4f18-bf13-a7bb4c22273a/editor)

Both have a code block (marked ) which is only for one-time contributors. Goal of this: to turn them into recurring contributors. 

**Used variables:** 

- {{insert first_name}} = First name of contributor
- {{currency}} = currency of the first donation
- {{donation-amount}} = donation amount
- {{n-days-ago}} = calculation of how many days ago a donation was made. For example: X donated on March 12, then on the day of the email dispatch (always 15th), it should say `3`. This makes the email more relevant and personal. 
- {{ author }} = the person sending the email, in this case it will be Aurélie Schmiedlin. It should correspond with the email used (aurelie@socialincoem.org)

What didn't work: Button for "monthly donation" pointing directly to ../me/subscriptions. But the login process doesn't remember the path, so I changed to ../login. 

Question: 
- @mkue should we keep a copy of the HTML in the repo? This would allow others to suggest changes directly in the code, without having access to sendgrid? Let me know and I'll check it in. 

**Basic sending rules:** 
- this should be sent to all first time contributors (one-time and recurring)
- this should **not** be sent  to existing recurring contributors who make their first one time payment
- always triggered on the 15th of every month (our pay day)
- only send one time to each contributor, never twice or more.

**Comment by mkue** [comment]
We need to completely different dymamic templates on Sendgrid, not two different versions.

<img width="1551" alt="Screenshot 2024-04-28 at 12 25 49" src="https://github.com/socialincome-san/public/assets/3518809/d736c9ea-2dab-44dc-bfd6-824ce378f296">

Can you move the German version over to the new template that I created? And can you change all template variables to use underscores, i.e `donation-amount` --> `donation_amount`?

Ping me when you're done, and then I'll test the email sending from the backend.

**Comment by ssandino** [comment]
Done @mkue now we have now the language version as separate dynamic templates. 

Changed following to underline: 
```
{{donation_amount}} 
{{n_days_ago}} 
{{donation_amount_sm}} 
{{donation_amount_md}}
```

We should probably update our plan before the upcoming 15th, as we have more new contributors through the campaign than our free version allows to send emails per day (100 per day).

**Comment by ssandino** [comment]
@mkue, you may need to update the 'unsubscribe' link in the emails, as it currently directs users to the general SendGrid site.

**Comment by mkue** [comment]
From what should the user unsubscribe from? It's a one-time email in this case... I think we could add link that adds the receiver to the global unsubscribe group on Sendgrid, then that person would not receive any email anymore...

**Comment by ssandino** [comment]
I appreciate the straightforwardness the "unsubscribe from all" option offers.

For the future, we could—though we don't have to—consider offering more granular control to our subscribers, especially given the capabilities that SendGrid provides. Two categories come to mind:

- Monthly Newsletter – For subscribers who prefer to stay updated but want to reduce the frequency of communications.
- Donor Transactional Emails – This category would include all communications related to one's donations, such as the initial donation confirmation, potential future impact reports, tax-related donation certificates, or invitations to convert to recurring donations.

Both options have their merits. Choose what you find technically better and right for the moment.
