### ISSUE TITLE
[Website Bug]: Not all navigation features work when JavaScript fails or is disabled

### ISSUE THREAD

**Issue by renestalder** [socialincome-san/public#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When JavaScript fails with runtime errors or is disabled completely, navigation items with sub items (fly-out/popover) can't be accessed.

Same goes for the menus: The language or region can only be changes if JavaScript is working correctly.

This isn't an issue with the new setup, but a long standing problem. Now with Next.js, we have new possibilities to enhance the behaviour between the server-side rendered/static versions and the client-side hydrated version.

### Steps To Reproduce

1. Go to socialincome.org
2. Open Chrome DevTools
3. Run command (CTRL+SHIFT+P or CMD+SHIFT+P) «Disable JavaScript»
4. Refresh page
5. Try to access transparency subpages or different languages.

### Expected Behavior

As a minimum functionality of a progressive enhanced website, the content navigation and access should work even when client-side scripting is failing its job. In the mentioned use cases, the navigations and menus should be progressively enhanced with client-side scripting, by falling back to sensible defaults:

- The sub navigation items should either already be expanded or the navigation to all sub pages should be possible by an index page e.g. «Transparency» page linking to it's subpages.
- The available languages and regions should be listed as links.

### Desktop Environment (please complete the following information)

```markdown
- OS: All
- Browser: All
- Version: All
```

### Smartphone Type (please complete the following information)

```markdown
- Device: All
- OS: All
- Browser: All
- Version: All
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by svrmnk** [comment]
I'd like to work on this!

I want to solve this task just making sub navigation items either already be expanded. That is, I will hide them using css and show them on hover or click with the expected animation. Will this solution suit?

**Comment by renestalder** [comment]
Hi @svrmnk 

> That is, I will hide them using css and show them on hover or click with the expected animation. Will this solution suit?

In addition, of course, on focus and on focus-within (for keyboard users).

I'm just not 100 % sure if CSS alone will be the best solution, considering there are some nuances to accessibility (not being able to navigate the same as mouse users due the non-existing expanded states) and usability (mouse movement over deltas of the corners). And Hover/Focused states will react differently on touch devices, that's another issue.

But I'm totally in for a merge request and you giving it a shot.

**Comment by svrmnk** [comment]
I fixed the bug with transparency sub-items, but I am stuck with the popup of languages. I consider, that this solition is the most suitable, when JS is crashed or disabled:
add "id" to popup component, than make button by <a> tag with href="id" and using css pseudo-class :target to add styles at popup.

Will this solution suit?

**Comment by svrmnk** [comment]
@renestalder, what do you think? Please, give me feedback. I also made PR with fixing this bug with transparency subitems, please check it: https://github.com/socialincome-san/public/pull/770
