### ISSUE TITLE
[Website Feature]: Merge terms of use, terms and conditions, privacy policy into one page, /legal

### ISSUE THREAD

**Issue by DarkMenacer** [socialincome-san/public#734]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Describe the solution/feature

- Create legal page and add three sections for each of the three pages (Privacy, site use, donations)
- Attach links to sections
- Polish CSS and make overall presentable (and responsive)

Order to the viewer: Privacy, site use, donations

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
thx @DarkMenacer

**Comment by DarkMenacer** [comment]
Draft PR created

**Comment by DarkMenacer** [comment]
PR ready to be merged
