### ISSUE TITLE
[Admin Tool Feature]: Adding email input validations for email form fields

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#755]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently we don't have an input validation for the email input fields in the Admin Tool. This applies to the contributor list, as well as the recipient list. 

<img width="749" alt="Screenshot 2024-02-28 at 22 34 36" src="https://github.com/socialincome-san/public/assets/6095849/046fb2f7-cd3f-4fed-a419-f677048a4a14">

A valid email address consists of three parts: an individual part, the at-sign @, and a domain name part. If any of these parts are missing, misspelt, or misplaced, an email address becomes invalid.

### Describe the solution/feature

This can be achieved by setting email flag to true in string property. See [Firecms Documentation](https://firecms.co/docs/properties/fields/text_fields#email-field)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by Riyazul555** [comment]
@ssandino I want to work on this issue
Assign me this thanks

**Comment by ntkzwane** [comment]
Hey there, could I grab this issue?
