### ISSUE TITLE
[Website Feature]: Remove region selection dropdown for surveys

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#759]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

In our surveys, we present an option for users to select their region via a dropdown. While the dropdown is not pre-selected (like on the our website), it also only lists `international` (and not `ch`). Regardless, a dropdown to choose region is not needed for the survey as the survey content remains identical across all regions.

Attached is a screenshot illustrating the survey in its current state, displaying the popup and the unnecessary dropdown. Although these screenshots are from the app, the survey is actually presented within an iframe, and it's often also accessed by recipients directly through a URL (for the ones without the app). Therefore, this issue is not specific to the app and a website issue. 

![1ABC6E95-E30F-4205-A20B-A9664300961E_1_101_o](https://github.com/socialincome-san/public/assets/6095849/4d7fb7ec-db56-47b7-b6ad-675f2be1c59d)

### Describe the solution/feature

The optimal solution is to remove the region selection dropdown from the survey interface. While implementing this change, it's crucial to ensure that the [main website](socialincome.org) remains unaffected, as it might utilize the same component.

### Anything else?

It is important to note that we should still provide the option to select the survey language, as we offer the surveys in both English and Krio.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by txpham209** [comment]
I would like to work on this issue.

**Comment by elizabeth-agada** [comment]
Is this issue still available for work? I'd love to contribute if it's not currently being worked on.

**Comment by ssandino** [comment]
@elizabeth-agada This issue is challenging as it requires some pre-work and backend knowledge, given that surveys are protected and only accessible to recipients, making it hard to simulate. Can we propose a different issue?

**Comment by elizabeth-agada** [comment]
Oh, okay
Yeah, sure, I can take on another issue.
And sorry for late response.

**Comment by ssandino** [comment]
@elizabeth-agada what about this #728?
