### ISSUE TITLE
[Admin] Missing logo in dark mode

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#76]
**Describe the bug**
There is still a placeholder logo in the dark version. Should be anyway the Social Income Icon (not logo):

<img width="300" alt="icon_color_trans_bg@2x" src="https://user-images.githubusercontent.com/6095849/190927334-0edc1adf-8f6a-4680-a274-3fb73df0705c.png">

Which is saved as SVG in the `shared/assets/logos/`

**Screenshot of issue**
![anew](https://user-images.githubusercontent.com/6095849/190926035-e299bcc7-fb19-4f83-9e97-fb8bb567ad15.gif)

**Comment by LunarMarathon** [comment]
Hi, which file or folder should I be looking into to fix this issue?

**Comment by ssandino** [comment]
The logo is referenced here:
`/admin/src/app/App.tsx`

The referenced logo is saved here:
`/admin/public/logo.svg`

You find the icon to display in this folder: 
`/shared/assets/logos/icon_color.svg`

Not sure how the icon in the dark mode gets in!

**Comment by Ilikepizza2** [comment]
Hello!
Is this issue being solved or can I be assigned?

**Comment by ssandino** [comment]
@LunarMarathon should I assign it to you, as you asked first? Otherwise I assign it to @Ilikepizza2

**Comment by ssandino** [comment]
A similar unassigned issue is #80, maybe for @Ilikepizza2 ?

**Comment by LunarMarathon** [comment]
Thanks for replying, I went through the files but couldn't find the source of the issue. I couldn't find where the code for dark mode is. Maybe you could inspect the site in dark mode and check in which file the that image is used

**Comment by ssandino** [comment]
@mkue do you have a clue where they hide the dark mode icon and give a hint to @LunarMarathon ?

**Comment by danicunhac** [comment]
@ssandino not sure if the other guys are going to work on this one, but if not, could you assign this one to me?

**Comment by ssandino** [comment]
@danicunhac let us know if you have any question!

**Comment by ssandino** [comment]
@danicunhac if you refork you will see that the dark mode issue got solved, so now you would only have to change the asset from the logo to the icon. Let us know if you want to continue – now it's a fast catch! ;-)
