### ISSUE TITLE
[Website Feature]: Disable cookie banner for surveys

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#760]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Currently, our surveys display a cookie banner that is originally intended for website visitors. This banner could potentially disrupt the user experience for recipients completing the surveys, particularly those who are speakers of Krio.

![08B4D98A-E42C-478A-8D43-86A43170AD0D_1_101_o](https://github.com/socialincome-san/public/assets/6095849/97e484ca-5520-4e7b-be38-2bc720f5b403)

### Describe the solution/feature

The cookie banner should either be completely removed or made inactive within the survey environment.

### Anything else?

While implementing this change, it's crucial to ensure that the main website remains unaffected, as it uses the same cookie banner component for various functionalities.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by irolinski** [comment]
I'd like to work on this. However, I am also having trouble logging in (using sign in with Google).
