### ISSUE TITLE
[Website Feature]: Update survey background color

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#761]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The current grey background used in our surveys does not align with the established color scheme of Social Income. 

![E3B90E65-475E-4CA5-9EB7-AD3964A0B138_1_101_o](https://github.com/socialincome-san/public/assets/6095849/529d3c3c-3413-4a80-a32d-2790e484999e)

Please note that the screenshot originates from an app that loads the React survey page as an iframe, which can also be directly accessed on the web. You find the survey code [here](https://github.com/socialincome-san/public/tree/main/website/src/app/%5Blang%5D/%5Bregion%5D/(survey-tool)/survey/%5Brecipient%5D/%5Bsurvey%5D).

### Describe the solution/feature

To resolve this issue, we propose either removing the grey background altogether or changing it to the standard blue color #EDF3FF that is consistently used across the Social Income.

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by devesh-2002** [comment]
May I take up this issue?

**Comment by ssandino** [comment]
With pleasure @devesh-2002 – as the survey part is not yet documented in the readme, could you document the basic steps on your side (how to test, open etc. surveys) while working on it? This would help for future changes on the surveys.

**Comment by devesh-2002** [comment]
Sure, I will try.

**Comment by devesh-2002** [comment]
Is the survey page accessible only after Sign In? When I try to Sign In with Google, it does not sign in.

**Comment by ssandino** [comment]
Can you write a short "hello" to hello@socialincome.org – then I add you to the staging admin tool.

**Comment by devesh-2002** [comment]
Done. Please check it.

**Comment by elizabeth-agada** [comment]
Is this issue still available for work? I'd love to contribute if it's not currently being worked on.
