### ISSUE TITLE
Failing `execute-draw` action 

### ISSUE THREAD

**Issue by mkue** [socialincome-san/public#818]
The `execute-draw` action is failing on merges into main. Can we try to fix this? :)

https://github.com/socialincome-san/public/actions?query=branch%3Amain

**Comment by ssandino** [comment]
@CluEleSsUK has it on the radar and mentioned already to look into it (he is traveling these days back to Zurich). Thanks @CluEleSsUK

**Comment by mkue** [comment]
seems to be resolved👌🏼
