### ISSUE TITLE
[UI / Design Feature]: Recreate UI components

### ISSUE THREAD

**Issue by renestalder** [socialincome-san/public#84]
To make the website code public, we need to recreate the UI components due to the current library being under proprietary license.

## Plan of action

The plan of action I will apply based my recommendation through my experience of building component and pattern libraries.

1. Setup a proper design system environment with [Storybook](https://storybook.js.org/) to build the future UI components for the web
2. Rebuild the UI components with [Tailwind](https://tailwindcss.com/) (for easier developer adaption, as discussed in the development team) and by presetting key design tokens in the Tailwind config.
3. Store in a subfolder called `ui`. This is the base for all design/ui related stuff and will hold key design principles and guidelines for all distribution channels (including native apps if required) and the place to store future, reusable web/html/js components.

## Current UI Components

* [UI inventory of the current components, collected by Sandino as Google Doc (Internal Link)](https://docs.google.com/document/d/1G2ahUB1wl8GDdX7TJkO1ovWzVEtFQKVsNYTIrdvgSx0/edit?usp=sharing)

**Comment by ssandino** [comment]
Closing this issue due to updated designs and advancements since its creation. Will open a new issue for implementation later.
