### ISSUE TITLE
[Website Bug]: carousel displays incorrect logos for quotes

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The recent redesign introduced an issue on the [landing page](https://socialincome.org/en/int) where the quotes and their corresponding authors are not accompanied by the correct logos. It always shows the UN logo instead.  

<img width="954" alt="Screenshot 2024-10-02 at 16 31 30" src="https://github.com/user-attachments/assets/c5426fc8-2f66-419a-998c-38e3af95a164">

### Expected Behavior

The respective logos of the organizations (worldbank.svg and logo-icrc.svg) should be shown. The correct logos have already been deployed and are saved [here](https://github.com/socialincome-san/public/tree/main/website/src/app/%5Blang%5D/%5Bregion%5D/(website)/(home)/(assets)). he issue occurs in [this component](https://github.com/socialincome-san/public/blob/main/website/src/app/%5Blang%5D/%5Bregion%5D/(website)/(home)/(components)/quotes-carousel.tsx), which is currently assigning the UN logo to every quote instead of the correct author-specific logos.

### Desktop Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Version:
```

### Smartphone Type (please complete the following information)

```markdown
- Device:
- OS:
- Browser:
- Version:
```

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by mdumond** [comment]
Addressed in https://github.com/socialincome-san/public/pull/930
