### ISSUE TITLE
[Web]: Enhance partner page

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#942]
### Is your feature request related to a problem? Please describe.

Optimizing the campaign page to enhance usability, improve SEO and encourage donations.

**Usability** 

- [x] add a circle around the X for closing a dialog box and make it sticky. The classes `bg-white rounded-full backdrop-invert-50 backdrop-opacity-50` might do the job. It must be addressed in the core component. Example from apple.com how it's sticky: 
![Image](https://github.com/user-attachments/assets/03b04a09-b7e0-4c57-812e-a15483a2d8b7)

**Improve SEO**

-  [x] Add a dedicated page for each partner using [dynamic routes](https://dev.to/stephengade/how-to-handle-dynamic-routing-in-nextjs-29gi). **Goal:** Our partner pages should be easily discoverable when someone searches for one of our partners on Google. For instance, the content of the dialog box for our partner “Aurora” should also be accessible at socialincome.org/partners/aurora-foundation. **URL Structure:** Use the partner’s "org-long-name" (e.g., “Aurora Foundation”) in the URL. Before using it, format the name to be URL-friendly by converting it to lowercase and removing special characters. **Page Content:** For now, each page should display the same content as shown in the dialog box.
-  [x] Add a permalink to each partner’s table entry on the partner page and within the dialog box. This will help search engines recognize and index these pages, as they’re not linked in the main navigation or elsewhere.
![Image](https://github.com/user-attachments/assets/df4c1354-6211-4cde-8eec-f41b1865be4c)

**Encourage donations**

- [x] Adding a visual element that displays on both the partner overview page and the detail view if a partner has an ongoing fundraiser. It can be just two fields in the `website-partners.json` with link and campaign text
![Image](https://github.com/user-attachments/assets/d6462d41-048f-4c27-9a5e-ed0f5540257d)
![Image](https://github.com/user-attachments/assets/31ece508-82dc-4261-8ca9-2a8225000f5e)

**Design**

- [x] Add an image next to the quote, using the `org-photo` field in `website-partners.json` if available. If no image is provided, simply display none. To clarify its purpose, consider renaming this field to `org-quote-photo` to indicate that it’s specifically for the quote and not the official organization photo.
![Image](https://github.com/user-attachments/assets/f9abfec0-211e-4b6a-a068-26af9da34b29)

### Code of Conduct

- [x] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by DarkMenacer** [comment]
### Progress comment:
- [ ] Usability
- [ ] Improve SEO
    - [ ] Dynamic Routes
    - [ ] Permalinks
- [ ] Encourage donations
- [ ] Design
