### ISSUE TITLE
[Web]: Mux video flickers when played on Safari

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#951]
### Describe the bug

In Safari, the poster image flickers briefly before the video starts playing, causing a "not so smooth" transition.
![Image](https://github.com/user-attachments/assets/2f683b2f-f53c-456b-9a09-5f930a228429)

### Desktop Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Version:
```

### Smartphone Type (please complete the following information)

```markdown
- Device:
- OS:
- Browser:
- Version:
```

### Code of Conduct

- [x] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
The flickering was really bothering me, so I played around with some fixes and found something that worked for me locally. Here’s what I ended up with—could you @mdumond try it out on your end and see if it resolves the issue for you too?

---

### Changes:

**1. Added a Dedicated Poster Layer**  
I added a `div` with an `<img>` for the poster. This ensures the poster remains visible until the video is fully ready to play.

```tsx
const posterRef = useRef<HTMLDivElement>(null);
```

```tsx
<div ref={posterRef} className="absolute inset-0 z-0">
    <img
        className="h-full w-full object-cover"
        src="https://image.mux.com/IPdwilTUVkKs2nK8zKZi5eKwbKhpCWxgsYNVxcANeFE/thumbnail.jpg?time=2"
        alt="Video Poster"
    />
</div>
```

**2. Managed Poster Visibility Dynamically**  
The poster's visibility is controlled using the `opacity` property. It fades out when the video is ready (`canplay` event) and fades back in when the video is paused.

```tsx
useEffect(() => {
    const video = videoElementRef.current;
    if (playing && video) {
        video.addEventListener('canplay', () => {
            if (posterRef.current) {
                posterRef.current.style.opacity = '0';
                posterRef.current.style.transition = 'opacity 0.5s ease';
            }
        });
        video.play();
    } else {
        video?.pause();
        if (posterRef.current) {
            posterRef.current.style.opacity = '1';
        }
    }
}, [playing]);
```

**3. Some Layering for `<MuxVideo>`**  
Added `z-10` to make sure the video plays above the poster layer.

```tsx
<MuxVideo
    ref={videoElementRef}
    className="h-full w-full object-cover z-10"
    playbackId="IPdwilTUVkKs2nK8zKZi5eKwbKhpCWxgsYNVxcANeFE"
    startTime={2}
    loop
    muted={muted}
    autoPlay={playing}
    playsInline
    onCanPlay={() => setPlaying(true)}
>
```

---

This worked for me—curious to know if it resolves the issue on your end as well or if it causes new problems.

**Comment by mdumond** [comment]
I'm testing this, for me when I pause the video and start it again, the video stays behind the poster image. 

If I revert locally 
```
useEffect(() => {
    const video = videoElementRef.current;
    if (playing && video) {
        video.addEventListener('canplay', () => {
            if (posterRef.current) {
                posterRef.current.style.opacity = '0';
                posterRef.current.style.transition = 'opacity 0.5s ease';
            }
        });
        video.play();
    } else {
        video?.pause();
        if (posterRef.current) {
            posterRef.current.style.opacity = '1';
        }
    }
}, [playing]);
```
to 
```
useEffect(() => {
    const video = videoElementRef.current;
    if (playing && video) {
        video.addEventListener('canplay', () => {
            if (posterRef.current) {
                posterRef.current.style.opacity = '0';
                posterRef.current.style.transition = 'opacity 0.5s ease';
            }
        });
        video.play();
    } else {
        videoElementRef.current?.pause();
    }
}, [playing]);
```
the pause behavior does not change, and the flickering at the start is not reverted
