### ISSUE TITLE
[Web]: Change flag from rectangular to round

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#977]
### Is your feature request related to a problem? Please describe.

On the transparency page, it would look better to display round flags (as we do in navigation) instead of rectangular ones. Reason: for consistency and a more visually appealing design.

![Image](https://github.com/user-attachments/assets/cffa4bb3-a952-42e5-bf60-205f11a6fd8c)

### Code of Conduct

- [x] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
@dnhn Thank you so much for your efficient and impactful support in enhancing Social Income’s website. By making it look better, you’re helping more people want to donate make a real difference for those living in poverty! There are two new issues that are flagged "help wanted". 

Let me know if you’d like to jump on a quick call to get to know each other. You can reach me at sandino@socialincome.org.

**Comment by dnhn** [comment]
Thanks @ssandino, glad I can help!

I’ll reach out to schedule a call when I have some time. Looking forward to collaborating more!
